from libraries.gen_class import Class

single_channel_fts_settings = Class()

single_channel_fts_settings.single_channel_fts_build_dict = {
                                                             '_common_settings': {'font': 'large'},
                                                           
                                                           
                                                             '_single_channel_fts_popup_starting_position_header_label': {'text': 'Starting Position(Blue):',
                                                                                                                      'position': (0, 0, 1, 1)},
                                                             '_single_channel_fts_popup_starting_position_lineedit': {'text': '10000',
                                                                                                                      'position': (0, 1, 1, 1)},
                                                             '_single_channel_fts_popup_integration_time_header_label': {'text': 'Integration Time(ms):',
                                                                                                                      'position': (0, 2, 1, 1)},
                                                             '_single_channel_fts_popup_integration_time_lineedit': {'text': '-10000',
                                                                                                                      'position': (0, 3, 1, 1)},
                                                             '_single_channel_fts_popup_stepper_motor_resource_name_header_label': {'text': 'Stepper Motor Resource Name:',
                                                                                                                       'position': (1, 0, 1, 1)},
                                                             '_single_channel_fts_popup_stepper_mortor_combobox': {'function': '_connect_to_com_port', 
                                                                                                                   'position': (1, 1, 1, 1)},
                                                             '_single_channel_fts_popup_ending_position_header_label': {'text': 'Ending Position(Red):',
                                                                                                                      'position': (1, 2, 1, 1)},
                                                             '_single_channel_fts_popup_ending_position_lineedit': {'text': '300000',
                                                                                                                      'position': (1, 3, 1, 1)},
                                                             '_single_channel_fts_popup_signal_channel_header_label': {'text': 'Signal Channel:',
                                                                                                                      'position': (2, 0, 1, 1)},
                                                             '_single_channel_fts_popup_signal_channel_lineedit': {'text': '0',
                                                                                                                      'position': (2, 1, 1, 1)},                                                      
                                                             '_single_channel_fts_popup_apodization_header_label': {'text': 'Apodization:',
                                                                                                                      'position': (2, 2, 1, 1)},
                                                             '_single_channel_fts_popup_apodization_lineedit': {'text': 'Boxcar',
                                                                                                                      'position': (2, 3, 1, 1)},
                                                             '_single_channel_fts_popup_step_size_header_label': {'text': 'Step Size:',
                                                                                                                      'position': (3, 0, 1, 1)},
                                                             '_single_channel_fts_popup_step_size_lineedit': {'text': '500',
                                                                                                                      'position': (3, 1, 1, 1)},                                                      
                                                             '_single_channel_fts_popup_0-path_position_header_label': {'text': '0-Path Position(mm):',
                                                                                                                      'position': (3, 2, 1, 1)},
                                                             '_single_channel_fts_popup_0-path_position_lineedit': {'text': '34.175',
                                                                                                                      'position': (3, 3, 1, 1)},
                                                             '_single_channel_fts_popup_pause_between_label': {'text': 'Pause between data taking(ms):',
                                                                                                                      'position': (4, 0, 1, 1)},
                                                             '_single_channel_fts_popup_pause_between_lineedit': {'text': '500',
                                                                                                                      'position': (4, 1, 1, 1)},                                                      
                                                             '_single_channel_fts_popup_DistPerStep_header_label': {'text': 'DistPerStep(nm):',
                                                                                                                      'position': (4, 2, 1, 1)},
                                                             '_single_channel_fts_popup_DistPerStep_lineedit': {'text': '250.39',
                                                                                                                      'position': (4, 3, 1, 1)},
                                                             '_single_channel_fts_popup_DistPerStep_paul_header_label': {'text': 'Pauls FTS 4.168',
                                                                                                                      'position': (5, 0, 1, 1)},
                                                             '_single_channel_fts_popup_DistPerStep_bill_header_label': {'text': 'Bills FTS 250.39',
                                                                                                                      'position': (5, 1, 1, 1)},   
                                                             '_single_channel_fts_popup_phone_email_header_label': {'text': '10-Digit Phone Number or e-mail address:',
                                                                                                                      'position': (6, 0, 1, 2)},
                                                             '_single_channel_fts_popup_phone_email_lineedit': {'text': ' ',
                                                                                                                      'position': (6, 1, 1, 2)},    
                                                             '_single_channel_fts_popup_select_carrier_header_label': {'text': 'Select Carrier:',
                                                                                                                      'position': (7, 0, 1, 1)},
                                                             '_single_channel_fts_popup_select_carrier_lineedit': {'text': ' ',
                                                                                                                      'position': (7, 1, 1, 1)},                                                                                                                                                                                                                                                                                      
                                                             '_single_channel_fts_popup_scan_pushbutton': {'text': 'Scan', 'function': '_dummy',
                                                                                                           'position': (8, 0, 1, 1)},
                                                             '_single_channel_fts_popup_pause_pushbutton': {'text': 'Pause', 'function': '_dummy',
                                                                                                            'position': (8, 1, 1, 1)}, 
                                                             '_single_channel_fts_popup_done_pushbutton': {'text': 'Done', 'function': '_dummy',
                                                                                                           'position': (8, 2, 1, 1)},   
                                                             '_single_channel_fts_popup_pause_between_label': {'text': 'Pause between data taking(ms):',
                                                                                                                      'position': (9, 0, 1, 1)},
                                                             '_single_channel_fts_popup_pause_between_lineedit': {'text': '500',
                                                                                                                      'position': (9, 1, 1, 1)},                                                      
                                                             '_single_channel_fts_popup_number_of_steps_header_label': {'text': 'Number of Steps:',
                                                                                                                      'position': (9, 2, 1, 1)},
                                                             '_single_channel_fts_popup_number_of_steps_header_label': {'text': '0',
                                                                                                                      'position': (9, 3, 1, 1)},
                                                             '_single_channel_fts_popup_highest_freq_header_label': {'text': 'Highest Freq(Ghz):',
                                                                                                                      'position': (10, 0, 1, 1)},
                                                             '_single_channel_fts_popup_highest_freq_header_label': {'text': '0',
                                                                                                                      'position': (10, 1, 1, 1)},                                                      
                                                             '_single_channel_fts_popup_current_position_header_label': {'text': 'Current Position(White):',
                                                                                                                      'position': (10, 2, 1, 1)},
                                                             '_single_channel_fts_popup_current_position_header_label': {'text': '0',
                                                                                                                      'position': (10, 3, 1, 1)}, 
                                                             '_single_channel_fts_popup_position_header_label': {'text': 'Position:',
                                                                                                                      'position': (11, 0, 1, 1)},
                                                             '_single_channel_fts_popup_position_header_label': {'text': '0',
                                                                                                                      'position': (11, 1, 1, 1)},                                                      
                                                             '_single_channel_fts_popup_time_average_header_label': {'text': 'Time Average:',
                                                                                                                      'position': (11, 2, 1, 1)},
                                                             '_single_channel_fts_popup_time_average_header_label': {'text': '0',
                                                                                                                      'position': (11, 3, 1, 1)}, 
                                                             '_single_channel_fts_popup_sd_header_label': {'text': 'Standard Dev:',
                                                                                                                      'position': (11, 0, 1, 1)},
                                                             '_single_channel_fts_popup_sd_header_label': {'text': '0',
                                                                                                                      'position': (11, 1, 1, 1)},                                                                                                                                                                                                                                                
                                                             }

single_channel_fts_settings.com_ports = ['COM1', 'COM2', 'COM3', 'COM4']

